### ISSUE TITLE
Summary needs to be escaped

### ISSUE THREAD

**Issue by WtfJoke** [rtcTo/rtc2jira#12]
The summary attribute of rtc contains escaped xml-elments like (`&amp; for &` and so on).
We need to unescape them before we import it or better save them already unescaped.

Using https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html?

**Comment by romixch** [comment]
I think we can detect if an attribute is actually html and then save this information along with the summary to detect it later at export.

**Comment by WtfJoke** [comment]
Yeah we could do that. The description of workitems are always html and the title sometime is

**Comment by romixch** [comment]
Saving unescaped is the proper solution...
