### ISSUE TITLE
Keep RTC WorkItem ID in JIRA

### ISSUE THREAD

**Issue by romixch** [rtcTo/rtc2jira#18]
We hope to be able to keep the RTC WorkItem ID in JIRA so that we can link from git repositories to the JIRA issue without a mapping file that maintains RTC IDs and JIRA IDs. Anyway it is easier for people to have the same numbers in JIRA too so they don't need to wrap their heads around the migration logic.

**Comment by WtfJoke** [comment]
Do you have an idea how to accomplish that? If the Jira-Id will be set, it will get ignored by the API.

The only way to get to a certain number would be creating so long issues until you get the requested number. But this is only possible once. Even if you delete all existing issue, the ids wont start from 1 anymore.

**Comment by romixch** [comment]
The only way seams to be this:
Create dummy issues until I reach the appropriate ID. I would therefore always make this two steps:
1. Drive the Jira-ID the current number (if not yet available)
2. Update Jira Issue.

**Comment by romixch** [comment]
This is fixed and available on master.
