### ISSUE TITLE
Connect git <-> JIRA

### ISSUE THREAD

**Issue by romixch** [rtcTo/rtc2jira#20]
If we migrate an RTC project with WorkItems and source code with rtc2jira and rtc2git we would like to see a connection between commits and WorkItems.

**Comment by WtfJoke** [comment]
When #18 is solved, no additional work in rtc2jira is needed. 
The enhancement is only needed in rtc2git and will be solved with [rtc2git#48](https://github.com/rtcTo/rtc2git/issues/48), therefore I close this issue here
