### ISSUE TITLE
Error seen when running the project

### ISSUE THREAD

**Issue by Maamalan** [rtcTo/rtc2jira#27]
I have followed all the steps provided in the ReadMe file. But I am getting compilation error. Attaching the same. Any help will be appreciated. Thanks.
[Compilation Error.txt](https://github.com/rtcTo/rtc2jira/files/2513860/Compilation.Error.txt)

**Comment by WtfJoke** [comment]
Hi Maamalan
Did you import the rtc libraries? Which version do you use?

**Comment by Maamalan** [comment]
Yes, I did get the latest rtc libraries. I have downloaded 6.0.5 version because that is the version of our RTC server.

**Comment by WtfJoke** [comment]
Sorry @Maamalan I didnt find the time to test it until now

On my side I havent any compilation failures, even using 6.0.5 version of the libraries.
Can you show me your configured user library from eclipse (you go there by right clicking the project --> build path --> configure build path? And also show a screenshot of your problems view in your workspace

The Libraries in build path should look like that:
![temp](https://user-images.githubusercontent.com/7139697/48941702-ed0d6180-ef1c-11e8-9539-7db452c8e382.PNG)

**Comment by WtfJoke** [comment]
Im closing this, feel free to reopen it if you still facing this problem
