### ISSUE TITLE
Can we migrate RTC sourcecode and workitems at the same time

### ISSUE THREAD

**Issue by himmakam** [rtcTo/rtc2jira#29]
Hi, we do have RTC to manage source code in one project area and workitems in another project area. And we do have linked code commits with workitems. Does this tool handle this migration by having that links between source code and workitem info intact. Please give me the suggestions

**Comment by himmakam** [comment]
so my main question was can we do the migration of both source code and workitems at the same time.

**Comment by himmakam** [comment]
We are planning to move both workitems and source code to GIT

**Comment by WtfJoke** [comment]
Yes, you can first migrate your rtc workitems/issues with this project(rtc2jira) to jira (or similar). 
E.g. You migrate it in a new jira project (for example a new project with key "RTC", and define it here [here](https://github.com/rtcTo/rtc2jira/blob/master/src/main/resources/settings.properties.example#L18)).

After that you can migrate with either [rtc2git](https://github.com/rtcTo/rtc2git)or [rtc2gitcli](https://github.com/rtcTo/rtc2gitcli) the source code commits. When you migrate them you can specify the project-key in the config (Config-Template for [rtc2git](https://github.com/rtcTo/rtc2git/blob/develop/config.ini.sample#L53) or [rtc2gitcli](https://github.com/rtcTo/rtc2gitcli/blob/master/migration.properties#L40)) .

**Comment by himmakam** [comment]
Thanks for your info. When I do the above settings and migrate the source code, does it link to the workitem in jira/git by making use of this projectkey?

**Comment by WtfJoke** [comment]
Yes, if you prefix the commits with the project key it does. 

See https://confluence.atlassian.com/jirasoftwarecloud/processing-issues-with-smart-commits-788960027.html#ProcessingissueswithSmartCommits-SmartCommitcommands for more information how code commit linking works
