### ISSUE TITLE
Can u tell me exactly which library to be downloaded

### ISSUE THREAD

**Issue by ybhavm** [rtcTo/rtc2jira#30]
Hi,
Can you please tell me exactly which library has to be downloaded? Since when i open the library link provided its going to Jazz common website. It would be helpful very much

**Comment by WtfJoke** [comment]
Hi @ybhavm 

![grafik](https://user-images.githubusercontent.com/7139697/73960547-6a977480-490b-11ea-914f-2b5b596b0d93.png)

As mentioned in the readme the "Plain Java Client Libraries" should do the job. 👍

**Comment by WtfJoke** [comment]
If you need further help, feel free to comment on this issue.

**Comment by ybhavm** [comment]
Hi @WtfJoke ,
Is this normal Java library that we download or do we have something called as Plain Java Library?
As i am unable to find such library on clicking the link provided in the Readme

**Comment by WtfJoke** [comment]
![rtc](https://user-images.githubusercontent.com/7139697/74593470-d1afda00-502b-11ea-8383-a1d8ef1b06e3.gif)

Have you seen my screenshot? See my gif... It does say Plain Java Library
