### ISSUE TITLE
When imported the code throws an errror

### ISSUE THREAD

**Issue by ybhavm** [rtcTo/rtc2jira#31]
Hi Team,
When i import the project in the eclipse and add the user library as mentioned, the code has an error as following:

ODocument cannot be resolved to a type.

Please let me know if something has to be done from my end or is there anything which you guys can support

**Comment by WtfJoke** [comment]
Hi @ybhavm 

The class you mention belongs to OrientDB, which is a [dependency of the project](https://github.com/rtcTo/rtc2jira/blob/master/pom.xml#L41-L45)

Therefor you should import the maven dependencies. You should run maven update in eclipse.

Hope that helps

**Comment by WtfJoke** [comment]
Closing that, assuming that it works.
If not, feel free to reopen
